export const APP_ROLES = ['admin', 'tutor', 'student', 'guardian', 'coaching'] as const;

export type AppRole = (typeof APP_ROLES)[number];

export const PERMISSIONS = {
  VIEW_PUBLIC: 'VIEW_PUBLIC',
  CREATE_TUITION: 'CREATE_TUITION',
  APPLY_TUITION: 'APPLY_TUITION',
  HIRE_TUTOR: 'HIRE_TUTOR',
  EDIT_PROFILE: 'EDIT_PROFILE',
  DELETE_PROFILE: 'DELETE_PROFILE',
  UPLOAD_DOCUMENT: 'UPLOAD_DOCUMENT',
  PAYMENT_REQUEST: 'PAYMENT_REQUEST',
  VIEW_ADMIN: 'VIEW_ADMIN',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_JOBS: 'MANAGE_JOBS',
  MANAGE_NOTICES: 'MANAGE_NOTICES',
  MANAGE_PAYMENTS: 'MANAGE_PAYMENTS',
  MANAGE_BLOGS: 'MANAGE_BLOGS',
  MANAGE_DOWNLOADS: 'MANAGE_DOWNLOADS',
  SAVE_TUTOR: 'SAVE_TUTOR',
  SAVE_JOB: 'SAVE_JOB',
  APPROVE_RESOURCE: 'APPROVE_RESOURCE',
  REJECT_RESOURCE: 'REJECT_RESOURCE',
  REVIEW_RESOURCE: 'REVIEW_RESOURCE',
  MANAGE_CALENDAR: 'MANAGE_CALENDAR',
  MANAGE_MESSAGES: 'MANAGE_MESSAGES',
  MANAGE_NOTIFICATIONS: 'MANAGE_NOTIFICATIONS',
} as const;

export type AppPermission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<AppRole, AppPermission[]> = {
  admin: Object.values(PERMISSIONS),
  tutor: [
    PERMISSIONS.VIEW_PUBLIC,
    PERMISSIONS.APPLY_TUITION,
    PERMISSIONS.EDIT_PROFILE,
    PERMISSIONS.DELETE_PROFILE,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.PAYMENT_REQUEST,
    PERMISSIONS.REVIEW_RESOURCE,
    PERMISSIONS.MANAGE_NOTIFICATIONS,
  ],
  student: [
    PERMISSIONS.VIEW_PUBLIC,
    PERMISSIONS.CREATE_TUITION,
    PERMISSIONS.HIRE_TUTOR,
    PERMISSIONS.EDIT_PROFILE,
    PERMISSIONS.DELETE_PROFILE,
    PERMISSIONS.SAVE_TUTOR,
    PERMISSIONS.SAVE_JOB,
    PERMISSIONS.MANAGE_MESSAGES,
  ],
  guardian: [
    PERMISSIONS.VIEW_PUBLIC,
    PERMISSIONS.CREATE_TUITION,
    PERMISSIONS.HIRE_TUTOR,
    PERMISSIONS.EDIT_PROFILE,
    PERMISSIONS.DELETE_PROFILE,
    PERMISSIONS.SAVE_TUTOR,
    PERMISSIONS.SAVE_JOB,
    PERMISSIONS.MANAGE_MESSAGES,
  ],
  coaching: [
    PERMISSIONS.VIEW_PUBLIC,
    PERMISSIONS.CREATE_TUITION,
    PERMISSIONS.EDIT_PROFILE,
    PERMISSIONS.DELETE_PROFILE,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.MANAGE_NOTICES,
    PERMISSIONS.MANAGE_CALENDAR,
    PERMISSIONS.MANAGE_NOTIFICATIONS,
  ],
};
